# Generated by Django 4.1 on 2022-09-05 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullstackapp', '0002_contactdetails_email_contactdetails_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('origin', models.CharField(max_length=200)),
                ('details', models.CharField(max_length=200)),
            ],
        ),
    ]
